### PR TITLE
increase tooltip font size

### PR DESCRIPTION
**Pull request by ctf0**
- go to def should have more space under it
- find a way to make the tooltip taller when there are more than one item

demo

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
Thanks! ok!

**Comment by pichillilorenzo** [comment]
@ctf0 Something like this?
schermata 2018-01-16 alle 20 09 00

**Comment by ctf0** [comment]
yes yes yes

**Comment by ctf0** [comment]
btw, how exactly go to def works, is shows up even if the tooltip have something like `string => string` is that normal ?

**Comment by pichillilorenzo** [comment]
mmmm yeah.. at the moment there isn't a check about that. It shows up in every tooltip, but I will try to manage that!

**Comment by ctf0** [comment]
maybe we can check if its anything other than string , or flow doesnt support that ?

**Comment by pichillilorenzo** [comment]
I think yes (In fact I need to check about that because I don't remember), but at this moment my time is very limited due to University exams 😞 .. However later I will try to check that 👍

**Comment by pichillilorenzo** [comment]
@ctf0 Done! Now tooltip wont show up on quoted strings and numeric constants. 
Furthermore the plugin is now available on Package Control 😄

**Comment by ctf0** [comment]
focken awesoooooooome :collision:

**Pull request merged**
